Repository GIGEDI/GIGEDI-BE, pull requests merged in 2024-11, with the labels that each got.

#16 [Feat] 토큰 재발급 로직 구현
  src/main/java/gigedi/dev/domain/auth/api/AuthController.java
  src/main/java/gigedi/dev/domain/auth/application/AuthService.java
  src/main/java/gigedi/dev/domain/auth/application/JwtTokenService.java
  src/main/java/gigedi/dev/domain/auth/domain/RefreshToken.java
  src/main/java/gigedi/dev/domain/auth/dto/AccessTokenDto.java
  src/main/java/gigedi/dev/domain/auth/dto/RefreshTokenDto.java
  src/main/java/gigedi/dev/domain/auth/dto/request/TokenRefreshRequest.java
  src/main/java/gigedi/dev/domain/member/domain/Member.java
  src/main/java/gigedi/dev/global/common/constants/SecurityConstants.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
  src/main/java/gigedi/dev/global/security/.gitkeep
  src/main/java/gigedi/dev/global/security/JwtAuthenticationFilter.java
  src/main/java/gigedi/dev/global/util/JwtUtil.java
  src/main/resources/logback-spring.xml
Labels: ✨ feature

#18 [Feat] 엔티티 생성
  src/main/java/gigedi/dev/domain/archive/api/.gitkeep
  src/main/java/gigedi/dev/domain/archive/application/.gitkeep
  src/main/java/gigedi/dev/domain/archive/dao/.gitkeep
  src/main/java/gigedi/dev/domain/archive/domain/Archive.java
  src/main/java/gigedi/dev/domain/archive/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/archive/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/auth/domain/Discord.java
  src/main/java/gigedi/dev/domain/auth/domain/Figma.java
  src/main/java/gigedi/dev/domain/block/api/.gitkeep
  src/main/java/gigedi/dev/domain/block/application/.gitkeep
  src/main/java/gigedi/dev/domain/block/dao/.gitkeep
  src/main/java/gigedi/dev/domain/block/domain/Block.java
  src/main/java/gigedi/dev/domain/block/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/block/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/file/api/.gitkeep
  src/main/java/gigedi/dev/domain/file/application/.gitkeep
  src/main/java/gigedi/dev/domain/file/dao/.gitkeep
  src/main/java/gigedi/dev/domain/file/domain/Authority.java
  src/main/java/gigedi/dev/domain/file/domain/File.java
  src/main/java/gigedi/dev/domain/file/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/file/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/member/domain/Member.java
  src/main/java/gigedi/dev/domain/member/domain/OauthInfo.java
  src/main/java/gigedi/dev/domain/shoot/api/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/application/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/dao/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/domain/Shoot.java
  src/main/java/gigedi/dev/domain/shoot/domain/ShootStatus.java
  src/main/java/gigedi/dev/domain/shoot/domain/ShootTag.java
  src/main/java/gigedi/dev/domain/shoot/domain/Status.java
  src/main/java/gigedi/dev/domain/shoot/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/dto/response/.gitkeep
  src/main/java/gigedi/dev/global/common/model/BaseTimeEntity.java
Labels: ✨ feature

#11 [Ci/cd] NCP 개발 환경 배포
  .github/workflows/dev-deploy.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: 🌏 deploy

#25 [Test] 회원 관련 주요 로직 테스트 작성
  src/test/java/gigedi/dev/domain/auth/application/AuthServiceTest.java
  src/test/java/gigedi/dev/domain/member/domain/MemberTest.java
  src/test/java/gigedi/dev/global/util/MemberUtilTest.java
  src/test/java/gigedi/dev/global/util/SecurityUtilTest.java
Labels: ✅ test

#28 [CI/CD] NCP → AWS CICD 수정
  .github/workflows/dev-deploy.yml
Labels: 🌏 deploy

#33 [Feat] 블록 관련 API 구현
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/gigedi/dev/domain/archive/application/.gitkeep
  src/main/java/gigedi/dev/domain/archive/application/ArchiveService.java
  src/main/java/gigedi/dev/domain/archive/dao/.gitkeep
  src/main/java/gigedi/dev/domain/archive/dao/ArchiveRepository.java
  src/main/java/gigedi/dev/domain/archive/domain/Archive.java
  src/main/java/gigedi/dev/domain/auth/dao/FigmaRepository.java
  src/main/java/gigedi/dev/domain/block/api/.gitkeep
  src/main/java/gigedi/dev/domain/block/api/BlockController.java
  src/main/java/gigedi/dev/domain/block/application/.gitkeep
  src/main/java/gigedi/dev/domain/block/application/BlockService.java
  src/main/java/gigedi/dev/domain/block/application/BlockTitleService.java
  src/main/java/gigedi/dev/domain/block/dao/.gitkeep
  src/main/java/gigedi/dev/domain/block/dao/BlockRepository.java
  src/main/java/gigedi/dev/domain/block/domain/Block.java
  src/main/java/gigedi/dev/domain/block/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/block/dto/request/CreateBlockRequest.java
  src/main/java/gigedi/dev/domain/block/dto/request/UpdateBlockRequest.java
  src/main/java/gigedi/dev/domain/block/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/block/dto/response/CreateBlockResponse.java
  src/main/java/gigedi/dev/domain/block/dto/response/GetBlockResponse.java
  src/main/java/gigedi/dev/global/common/constants/FigmaConstants.java
  src/main/java/gigedi/dev/global/common/constants/HeaderConstants.java
  src/main/java/gigedi/dev/global/config/WebSecurityConfig.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
  src/main/java/gigedi/dev/global/interceptor/FigmaInfoInterceptor.java
  src/main/java/gigedi/dev/global/util/FigmaUtil.java
Labels: ✨ feature

#36 [Fix] 코드리뷰 수정사항 중 빠르게 변경할 수 있는 부분 수정
  build.gradle
  gradle.properties
  src/main/java/gigedi/dev/domain/archive/domain/Archive.java
  src/main/java/gigedi/dev/domain/auth/domain/Discord.java
  src/main/java/gigedi/dev/domain/auth/domain/Figma.java
  src/main/java/gigedi/dev/domain/block/domain/Block.java
  src/main/java/gigedi/dev/domain/config/BaseTimeEntity.java
  src/main/java/gigedi/dev/domain/file/domain/Authority.java
  src/main/java/gigedi/dev/domain/member/domain/Member.java
  src/main/java/gigedi/dev/domain/shoot/domain/Shoot.java
  src/main/java/gigedi/dev/domain/shoot/domain/ShootStatus.java
  src/main/java/gigedi/dev/domain/shoot/domain/ShootTag.java
  src/main/java/gigedi/dev/domain/shoot/domain/Status.java
  src/main/resources/application-datasource.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-log.yaml
  src/main/resources/application-security.yaml
Labels: ⚙️ fix

#37 [Feat] 아카이브 CRUD 구현
  src/main/java/gigedi/dev/domain/archive/api/.gitkeep
  src/main/java/gigedi/dev/domain/archive/api/ArchiveController.java
  src/main/java/gigedi/dev/domain/archive/application/ArchiveService.java
  src/main/java/gigedi/dev/domain/archive/application/ArchiveTitleService.java
  src/main/java/gigedi/dev/domain/archive/dao/ArchiveRepository.java
  src/main/java/gigedi/dev/domain/archive/domain/Archive.java
  src/main/java/gigedi/dev/domain/archive/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/archive/dto/request/CreateArchiveRequest.java
  src/main/java/gigedi/dev/domain/archive/dto/request/UpdateArchiveRequest.java
  src/main/java/gigedi/dev/domain/archive/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/archive/dto/response/ArchiveInfoResponse.java
  src/main/java/gigedi/dev/domain/file/domain/File.java
  src/main/java/gigedi/dev/global/common/constants/FigmaConstants.java
  src/main/java/gigedi/dev/global/config/SwaggerConfig.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
Labels: ✨ feature

#39 [Feat] 토큰 활용 멤버 정보 조회
  src/main/java/gigedi/dev/domain/member/api/MemberController.java
  src/main/java/gigedi/dev/domain/member/application/MemberService.java
Labels: ✨ feature

#40 [Feat] 피그마 계정 연동 구현
  build.gradle
  src/main/java/gigedi/dev/domain/auth/api/AuthController.java
  src/main/java/gigedi/dev/domain/auth/application/AuthService.java
  src/main/java/gigedi/dev/domain/auth/application/FigmaService.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaTokenResponse.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaUserResponse.java
  src/main/java/gigedi/dev/domain/auth/dto/response/UserInfoResponse.java
  src/main/java/gigedi/dev/global/common/constants/SecurityConstants.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
  src/main/java/gigedi/dev/infra/config/PropertiesConfig.java
  src/main/java/gigedi/dev/infra/config/oauth/FigmaProperties.java
  src/main/resources/application-security.yaml
  src/test/java/gigedi/dev/global/util/SecurityUtilTest.java
Labels: ✨ feature

#42 [Feat] 디스코드 연결 구현
  build.gradle
  src/main/java/gigedi/dev/domain/auth/application/GoogleService.java
  src/main/java/gigedi/dev/domain/auth/domain/Discord.java
  src/main/java/gigedi/dev/domain/discord/api/DiscordAuthController.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordAuthApiService.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordAuthService.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordDmApiService.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordGuildApiService.java
  src/main/java/gigedi/dev/domain/discord/application/ImageConverter.java
  src/main/java/gigedi/dev/domain/discord/dao/DiscordRepository.java
  src/main/java/gigedi/dev/domain/discord/domain/Discord.java
  src/main/java/gigedi/dev/domain/discord/dto/response/CreateDMChannelResponse.java
  src/main/java/gigedi/dev/domain/discord/dto/response/DiscordInfoResponse.java
  src/main/java/gigedi/dev/domain/discord/dto/response/DiscordLoginResponse.java
  src/main/java/gigedi/dev/domain/discord/dto/response/DiscordUserResponse.java
  src/main/java/gigedi/dev/global/common/constants/SecurityConstants.java
  src/main/java/gigedi/dev/global/config/RestClientConfig.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
  src/main/java/gigedi/dev/infra/config/PropertiesConfig.java
  src/main/java/gigedi/dev/infra/config/oauth/DiscordProperties.java
  src/main/resources/application-security.yaml
  src/main/resources/img/shoot.png
Labels: ✨ feature

#43 [CI/CD] 최신 코드를 빌드하지 못 하는 이슈 해결
  .github/workflows/dev-deploy.yml
  Dockerfile
Labels: 🌏 deploy

#45 [Feat] 연동된 피그마 계정 조회, 연동 해제 기능 구현
  src/main/java/gigedi/dev/domain/auth/api/AuthController.java
  src/main/java/gigedi/dev/domain/auth/application/AuthService.java
  src/main/java/gigedi/dev/domain/auth/dao/FigmaRepository.java
  src/main/java/gigedi/dev/domain/auth/domain/Figma.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaAccountResponse.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
Labels: ✨ feature

#51 [Bug] 구글 소셜 로그인 오류 해결
  src/main/java/gigedi/dev/domain/auth/application/AuthService.java
Labels: ✨ feature

#53 [Feat] 디스코드 계정 개수 제한 적용
  src/main/java/gigedi/dev/domain/discord/api/DiscordAuthController.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordAuthService.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordService.java
  src/main/java/gigedi/dev/domain/discord/dao/DiscordRepository.java
  src/main/java/gigedi/dev/domain/discord/domain/Discord.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
Labels: ✨ feature

#59 [Feat] Shoot API 구현
  src/main/java/gigedi/dev/domain/shoot/api/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/api/ShootController.java
  src/main/java/gigedi/dev/domain/shoot/application/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/application/ShootService.java
  src/main/java/gigedi/dev/domain/shoot/application/ShootStatusService.java
  src/main/java/gigedi/dev/domain/shoot/dao/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/dao/ShootRepository.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootStatusRepository.java
  src/main/java/gigedi/dev/domain/shoot/domain/Shoot.java
  src/main/java/gigedi/dev/domain/shoot/domain/ShootStatus.java
  src/main/java/gigedi/dev/domain/shoot/dto/request/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/dto/request/UpdateShootStatusRequest.java
  src/main/java/gigedi/dev/domain/shoot/dto/response/.gitkeep
  src/main/java/gigedi/dev/domain/shoot/dto/response/GetShootResponse.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
  src/main/java/gigedi/dev/global/util/TimeUtil.java
Labels: ✨ feature

#61 [Feat] 디스코드 알람 파일 조회
  .gitignore
  build.gradle
  src/main/java/gigedi/dev/domain/discord/api/AlarmController.java
  src/main/java/gigedi/dev/domain/discord/application/AlarmService.java
  src/main/java/gigedi/dev/domain/discord/application/DiscordService.java
  src/main/java/gigedi/dev/domain/discord/dto/response/AlarmFileResponse.java
  src/main/java/gigedi/dev/domain/discord/dto/response/GetAlarmFileListResponse.java
  src/main/java/gigedi/dev/domain/file/application/AuthorityService.java
  src/main/java/gigedi/dev/domain/file/dao/AuthorityRepository.java
  src/main/java/gigedi/dev/domain/file/dao/AuthorityRepositoryCustom.java
  src/main/java/gigedi/dev/domain/file/dao/AuthorityRepositoryImpl.java
  src/main/java/gigedi/dev/domain/member/domain/Member.java
  src/main/java/gigedi/dev/global/util/MemberUtil.java
Labels: ✨ feature

#63 [Feat] 디스코드 파일 알람 활성화 및 비활성화
  src/main/java/gigedi/dev/domain/discord/api/AlarmController.java
  src/main/java/gigedi/dev/domain/discord/application/AlarmService.java
  src/main/java/gigedi/dev/domain/discord/dto/response/AlarmFileResponse.java
  src/main/java/gigedi/dev/domain/figma/application/FigmaService.java
  src/main/java/gigedi/dev/domain/file/application/AuthorityService.java
  src/main/java/gigedi/dev/domain/file/dao/AuthorityRepositoryCustom.java
  src/main/java/gigedi/dev/domain/file/dao/AuthorityRepositoryImpl.java
  src/main/java/gigedi/dev/domain/file/domain/Authority.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
Labels: ✨ feature

#64 [Feat] Shoot 생성 API 구현, 상태 변경 수정
  src/main/java/gigedi/dev/domain/auth/dao/FigmaRepository.java
  src/main/java/gigedi/dev/domain/figma/application/FigmaService.java
  src/main/java/gigedi/dev/domain/shoot/api/ShootController.java
  src/main/java/gigedi/dev/domain/shoot/application/ShootService.java
  src/main/java/gigedi/dev/domain/shoot/application/ShootStatusService.java
  src/main/java/gigedi/dev/domain/shoot/application/ShootTagService.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootStatusRepository.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootTagRepository.java
  src/main/java/gigedi/dev/domain/shoot/dto/request/CreateShootRequest.java
  src/main/java/gigedi/dev/global/util/ShootUtil.java
Labels: ✨ feature

#69 [Fix] Block dto record로 수정
  src/main/java/gigedi/dev/domain/block/application/BlockService.java
  src/main/java/gigedi/dev/domain/block/dto/request/CreateBlockRequest.java
  src/main/java/gigedi/dev/domain/block/dto/request/UpdateBlockRequest.java
  src/main/java/gigedi/dev/domain/block/dto/response/CreateBlockResponse.java
  src/main/java/gigedi/dev/domain/block/dto/response/GetBlockResponse.java
Labels: ⚙️ fix

#67 [Feat] Our Shoot 조회 API 구현
  src/main/java/gigedi/dev/domain/shoot/api/ShootController.java
  src/main/java/gigedi/dev/domain/shoot/application/ShootService.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootRepository.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootRepositoryCustom.java
  src/main/java/gigedi/dev/domain/shoot/dao/ShootRepositoryImpl.java
  src/main/java/gigedi/dev/domain/shoot/dto/response/GetOurShootResponse.java
  src/main/java/gigedi/dev/global/error/exception/ErrorCode.java
Labels: ✨ feature

#72 [Feat] Redis 설정
  build.gradle
  docker-compose.yml
  src/main/java/gigedi/dev/infra/config/PropertiesConfig.java
  src/main/java/gigedi/dev/infra/config/redis/RedisConfig.java
  src/main/java/gigedi/dev/infra/config/redis/RedisProperties.java
  src/main/resources/application-redis.yaml
  src/main/resources/application.yaml
Labels: ✨ feature

#74 [Fix] 리프레시 토큰 저장을 redis로 수정
  src/main/java/gigedi/dev/domain/auth/application/JwtTokenService.java
  src/main/java/gigedi/dev/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/gigedi/dev/domain/auth/domain/RefreshToken.java
  src/main/java/gigedi/dev/domain/auth/dto/RefreshTokenDto.java
  src/main/java/gigedi/dev/global/util/JwtUtil.java
  src/test/java/gigedi/dev/domain/auth/application/AuthServiceTest.java
Labels: ⚙️ fix

#75 [Bug] 피그마 로그인 시 응답을 받지 못하는 오류 해결
  .gitignore
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaAccountResponse.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaTokenResponse.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaUserResponse.java
Labels: 🐛 bug/error

#76 [Bug] 피그마 연결 계정 조회 시 반환 id값 수정
  src/main/java/gigedi/dev/domain/auth/application/AuthService.java
  src/main/java/gigedi/dev/domain/auth/dto/response/FigmaAccountResponse.java
Labels: 🐛 bug/error
